export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_UPDATE = "USER UPDATED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const PROFILE_ANALYSIS_LOADING = "PROFILE_ANALYSIS_LOADING";

export const PROFILE_CREATED = "PROFILE_CREATED";
export const PROFILE_UPDATED = "PROFILE_UPDATED";
export const PROFILE_LOADED = "PROFILE_LOADED";
export const NO_PROFILE_FOUND = "NO_PROFILE_FOUND";
export const PROFILE_ANALYSIS_LOADED = "PROFILE_ANALYSIS_LOADED";

export const JOBS_LOADING = "JOBS_LOADING";
export const JOBS_LOADED = "JOBS_LOADED";
export const JOB_MATCHES_LOADED = "JOB_MATCHES_LOADED";
